language: python
python:
- '3.4'
cache: pip
install:
- pip install -r requirements.txt
before_script:
- git config --global user.email "travis-ci@travis.org"
- git config --global user.name "me via travis ci"
- rm -rf output
- git clone --quiet https://${GH_TOKEN}@github.com/sebastian-schmidt/sebastian-schmidt.github.io
  -b master output > /dev/null
script:
- nikola clean
- nikola build
after_success:
- cd output
- git add .
- git commit -m "[ci skip] Update output from Travis CI"
- git push origin master


